Fix examples by using `Cargo.lock` to build Modal image
Right now we only use `Cargo.toml` during the image build
which might resolve to a different set of Rust dependencies
at image build time. Using `Cargo.lock` gives us reproducible
image builds.

Right now the examples are broken because of a quinn-proto
compilation error. I think a newer version of quinn-proto was
released that uses `quinn_proto.Connection.set_send_window()`,
but the version of github.com/danielshaar/quinn that's pinned
in `Cargo.toml` only has `quinn_proto.Connection.set_receive_window()`.

```
❯ MODAL_PROFILE=modal-labs modal run examples/modal_simple.py
✓ Initialized. View run at https://modal.com/apps/modal-labs/dxia-dev/ap-53lpZWl9oEmdKMmvUVF0EN
Building image im-U44uMAWfrudFCABbXhi8Uc

=> Step 0: FROM base

=> Step 1: COPY . /
Saving image...
Image saved, took 952.87ms

Built image im-U44uMAWfrudFCABbXhi8Uc in 2.80s

Building image im-eHIXcepj75JOUL08xNOKV6

=> Step 0: FROM base

=> Step 1: RUN cd /tmp/quic-portal && . $HOME/.cargo/env && maturin build --release
    Updating git repository `https://github.com/danielshaar/quinn.git`
    Updating crates.io index
     Locking 196 packages to latest compatible versions
      Adding pyo3 v0.25.1 (available: v0.26.0)
      Adding rcgen v0.12.1 (available: v0.14.3)
      Adding socket2 v0.5.10 (available: v0.6.0)
      Adding thiserror v1.0.69 (available: v2.0.16)
 Downloading crates ...
 ...
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support
🐍 Not using a specific python interpreter
📡 Using build options features from pyproject.toml
   Compiling libc v0.2.175
   ...
   Compiling quinn-proto v0.11.13 (https://github.com/danielshaar/quinn.git#a776bad2)
error[E0599]: no method named `set_send_window` found for struct `quinn_proto::Connection` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/quinn-0.11.9/src/connection.rs:633:20
    |
633 |         conn.inner.set_send_window(send_window);
    |                    ^^^^^^^^^^^^^^^
    |
help: there is a method `set_receive_window` with a similar name
    |
633 -         conn.inner.set_send_window(send_window);
633 +         conn.inner.set_receive_window(send_window);
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `quinn` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_CONFIG_FILE="/tmp/quic-portal/target/maturin/pyo3-config-x86_64-unknown-linux-gnu-3.9.txt" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/quic-portal/Cargo.toml" "--release" "--lib"`
Terminating task due to error: failed to run builder command "cd /tmp/quic-portal && . $HOME/.cargo/env && maturin build --release": container exit status: 1
Runner failed with exit code: -1
Stopping app - uncaught exception raised locally: RemoteError('Image build for im-eHIXcepj75JOUL08xNOKV6 failed. See build logs for more details.').
╭─ Error ─────────────────────────────────────────────────────────────────────────────────╮
│ Image build for im-eHIXcepj75JOUL08xNOKV6 failed. See build logs for more details.      │
╰─────────────────────────────────────────────────────────────────────────────────────────╯
```

Signed-off-by: David Xia <dxia@modal.com>